name: Daily Flight Data Refresh

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily at 6:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      - name: Install dependencies
        run: pip install requests pandas openpyxl
      - name: Run script
        run: python .github/workflows/data-updater.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Commit and push xlsx
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout master
          git add flight_prices_all.xlsx
          git commit -m "Auto-update flight prices" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/PRODG25/tripsaver-data-updater.git master



