name: Daily Flight Data Refresh

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily at 6:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      - name: Install dependencies
        run: pip install os requests pandas
      - name: Run script
        run: python .github/workflows/data-updater.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
